# spring:
#   datasource:
#     driver-class-name: org.h2.Driver
#     url: jdbc:h2:mem:localhost;DB_CLOSE_ON_EXIT=FALSE
#     username: admin
#     password:

spring:
  datasource:
    # url: jdbc:h2:mem:mydb
    url: jdbc:h2:file:/Users/macpro/Documents/db
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
